# Generated by Django 5.2.4 on 2025-07-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingrecord',
            name='parking_name',
            field=models.CharField(default='Default Parking', max_length=100),
            preserve_default=False,
        ),
    ]
