# Generated by Django 5.2.4 on 2025-07-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('others', 'others')], default='car', max_length=20),
        ),
    ]
