# Generated by Django 5.2.4 on 2025-07-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_alter_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingrecord',
            name='parking_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='parkingrecord',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('free', 'Free (Monthly Pass)')], default='pending', max_length=20),
        ),
    ]
