# Generated by Django 5.2.4 on 2025-07-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_pricingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='parking_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
